language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B

deploy:
  provider: s3
  access_key_id:
    secure: "h0yKazhvbmUkYxwEvKhciCHufknS2ibfOhWXz3wEZQxG1qO3fehjjIk/rQTvLAMC9geXnFIDDlIToA9gnE9/6VDaO1ViEiw+h27ClzUzWhtpoC0ykNVnEojNr2bphrxRN7e+2/NjZssSBiKpK5JaDqzk8jgX1C+8puvE1VK28k0="
  secret_access_key:
    secure: "PgEwRtjdVzRSN4Dko4spasZjKJuVNGrZgYmaHjbUVd4aY8YFRGbcEEI2grOPqUkf9IIOKncnQtf4D8uFEH42nr836tCYzKwgaBsbn0Hmrq6zs29GNDJAeQy58PAxjdS8gi+YU7UPVZOPUyMWpbBNdgZTONHPtSm3k5x2o4Le9W8="
  bucket: oss.forter.com
  local-dir: /home/travis/.m2/repository/com/forter/storm-topology-api/
  upload-dir: repository/com/forter/storm-topology-api
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
